package com.bank.islamic.ijaraleasing;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Ijara Leasing
 *
 * Business Area:      Islamic Financing
 * Business Domain:    Lease And Partnership Financing
 * Functional Pattern: Fulfill
 * Asset Type:         Ijara Lease
 * Control Record:     Ijara Lease Fulfillment Arrangement
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Ijara Leasing — BIAN Semantic API")
                .description("Service Domain 'Ijara Leasing' (Fulfill pattern) "
                        + "operating on the 'Ijara Lease Fulfillment Arrangement' control record.")
                .version("0.1.0"));
    }
}
